In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
df = pd.DataFrame(iris['data'], columns=iris['feature_names'])
df['class'] = iris['target']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [4]:
classifier = tf.estimator.DNNClassifier(
    feature_columns=['class'],
    hidden_units=[3],
    n_classes=3)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpo60i55z_', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2e136b4ba8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [5]:
def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    return dataset.shuffle(1000).repeat().batch(batch_size)

## no...

In [1]:
import os
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow.contrib.eager as tfe

tf.enable_eager_execution()

print("TensorFlow version: {}".format(tf.VERSION))
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 1.11.0
Eager execution: True


In [2]:
train_dataset_url = "http://download.tensorflow.org/data/iris_training.csv"

train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))

Local copy of the dataset file: /home/miles/.keras/datasets/iris_training.csv


In [3]:
# column order in CSV file
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

feature_names = column_names[:-1]
label_name = column_names[-1]

print("Features: {}".format(feature_names))
print("Label: {}".format(label_name))

Features: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Label: species


In [4]:
class_names = ['Iris setosa', 'Iris versicolor', 'Iris virginica']

In [5]:
batch_size = 32

train_dataset = tf.contrib.data.make_csv_dataset(
    train_dataset_fp,
    batch_size, 
    column_names=column_names,
    label_name=label_name,
    num_epochs=1)

In [13]:
features, labels = next(iter(train_dataset))

features

<tf.Tensor: id=225, shape=(32, 4), dtype=float32, numpy=
array([[5.7, 2.9, 4.2, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.1, 3.8, 1.9, 0.4],
       [6.5, 3. , 5.5, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [4.9, 3. , 1.4, 0.2],
       [6.7, 3. , 5. , 1.7],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 2.2, 4.5, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.2, 5. , 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 3.1, 4.4, 1.4],
       [7. , 3.2, 4.7, 1.4],
       [4.9, 2.5, 4.5, 1.7],
       [4.6, 3.2, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [6. , 3. , 4.8, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3.7, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.7, 4.9, 1.8],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 2.5, 5. , 1.9]], dtype=float32)

In [18]:
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.stack(list(features.values()), axis=1)
  return features, labels

In [19]:
train_dataset = train_dataset.map(pack_features_vector)

AttributeError: 'Tensor' object has no attribute 'values'

In [53]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(100000, activation=tf.nn.relu),
  tf.keras.layers.Dense(3)
])

In [54]:
predictions = model(features)
predictions[:5]

<tf.Tensor: id=1363093, shape=(5, 3), dtype=float32, numpy=
array([[ 0.01551928, -0.03270797,  0.03872812],
       [ 0.01816303, -0.03685416,  0.04233136],
       [ 0.00709033, -0.02199557,  0.03539577],
       [ 0.02313096, -0.04522655,  0.04447079],
       [ 0.02262866, -0.04265703,  0.04037442]], dtype=float32)>

In [55]:
tf.nn.softmax(predictions[:5])

<tf.Tensor: id=1363099, shape=(5, 3), dtype=float32, numpy=
array([[0.33597663, 0.32015792, 0.34386545],
       [0.33659473, 0.31857646, 0.34482878],
       [0.33332857, 0.32377306, 0.3428984 ],
       [0.3383527 , 0.3159966 , 0.3456507 ],
       [0.3384434 , 0.31705368, 0.34450293]], dtype=float32)>

In [56]:
print("Prediction: {}".format(tf.argmax(predictions, axis=1)))
print("    Labels: {}".format(labels))

Prediction: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
    Labels: [1 1 0 2 2 0 1 1 1 0 0 2 2 0 1 2 2 1 1 2 0 0 1 2 2 2 0 2 2 2 1 2]


In [57]:
def loss(model, x, y):
  y_ = model(x)
  return tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_)

In [58]:
l = loss(model, features, labels)
print("Loss test: {}".format(l))

Loss test: 1.097434401512146


In [59]:
def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

In [60]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

global_step = tf.train.get_or_create_global_step()

In [61]:
loss_value, grads = grad(model, features, labels)

print("Step: {}, Initial Loss: {}".format(global_step.numpy(),
                                          loss_value.numpy()))

optimizer.apply_gradients(zip(grads, model.variables), global_step)

print("Step: {},         Loss: {}".format(global_step.numpy(),
                                          loss(model, features, labels).numpy()))

Step: 6406, Initial Loss: 1.097434401512146
Step: 6407,         Loss: 1.0330499410629272


In [62]:
## Note: Rerunning this cell uses the same model variables

# keep results for plotting
train_loss_results = []
train_accuracy_results = []

num_epochs = 401

for epoch in range(num_epochs):
  epoch_loss_avg = tfe.metrics.Mean()
  epoch_accuracy = tfe.metrics.Accuracy()

  # Training loop - using batches of 32
  for x, y in train_dataset:
    # Optimize the model
    loss_value, grads = grad(model, x, y)
    optimizer.apply_gradients(zip(grads, model.variables),
                              global_step)

    # Track progress
    epoch_loss_avg(loss_value)  # add current batch loss
    # compare predicted label to actual label
    epoch_accuracy(tf.argmax(model(x), axis=1, output_type=tf.int32), y)

  # end epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())
  
  if epoch % 50 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))

Epoch 000: Loss: 1.050, Accuracy: 35.000%
Epoch 050: Loss: 0.355, Accuracy: 92.500%
Epoch 100: Loss: 0.231, Accuracy: 98.333%
Epoch 150: Loss: 0.155, Accuracy: 97.500%
Epoch 200: Loss: 0.137, Accuracy: 98.333%
Epoch 250: Loss: 0.109, Accuracy: 98.333%
Epoch 300: Loss: 0.104, Accuracy: 97.500%
Epoch 350: Loss: 0.128, Accuracy: 97.500%
Epoch 400: Loss: 0.097, Accuracy: 95.833%
